import styled from 'styled-components';

export default styled.div`
  ${({ display }) => display && `display : ${display}`};
  width: ${({ width }) => width};
  height: ${({ height }) => height};
  position: ${({ position }) => position};
  top: ${({ top }) => top};
  right: ${({ right }) => right};
  bottom: ${({ bottom }) => bottom};
  left: ${({ left }) => left};
  flex: ${({ flex }) => flex};
  grid-template-columns: ${({ gridTemplateColumns }) => gridTemplateColumns};
  gap: ${({ gap }) => gap};
  align-content: ${({ alignContent }) => alignContent};
  justify-content: ${({ justifyContent }) => justifyContent};
  justify-items: ${({ justifyItems }) => justifyItems};
  place-items: ${({ placeItems }) => placeItems};
  flex-direction: column;
  ${({ flexWrap }) => flexWrap && `flex-wrap : ${flexWrap}`};
  ${({ flexShrink }) => flexShrink && `flex-shrink : ${flexShrink}`};
  ${({ alignItems }) => alignItems && `align-items : ${alignItems}`};
  vertical-align: ${({ verticalAlign }) => verticalAlign};
  text-align: ${({ textAlign }) => textAlign};
  margin: ${({ margin }) => margin};
  ${({ marginTop }) => marginTop && `margin-top : ${marginTop}`};
  ${({ marginRight }) => marginRight && `margin-right : ${marginRight}`};
  ${({ marginBottom }) => marginBottom && `margin-bottom : ${marginBottom}`};
  ${({ marginLeft }) => marginLeft && `margin-left : ${marginLeft}`};
  padding: ${({ padding }) => {
    return padding;
  }};
  ${({ paddingTop }) => paddingTop && `padding-top : ${paddingTop}`};
  ${({ paddingRight }) => paddingRight && `padding-right : ${paddingRight}`};
  ${({ paddingBottom }) => paddingBottom && `padding-bottom : ${paddingBottom}`};
  ${({ paddingLeft }) => paddingLeft && `padding-left : ${paddingLeft}`};
  ${({ height }) => height && `height : ${height}`};
  ${({ minHeight }) => minHeight && `min-height : ${minHeight}`};
  ${({ maxHeight }) => maxHeight && `max-height : ${maxHeight}`};
  ${({ width }) => width && `width : ${width}`};
  ${({ maxWidth }) => maxWidth && `max-width : ${maxWidth}`};
  background: ${({ background }) => background};
  background-image: ${({ backgroundImage }) => backgroundImage};
  background-repeat: ${({ backgroundRepeat }) => backgroundRepeat};
  color: ${({ color }) => color};
  border: ${({ border }) => border};
  border-right: ${({ borderRight }) => borderRight};
  border-bottom: ${({ borderBottom }) => borderBottom};
  border-radius: ${({ borderRadius }) => borderRadius};
  box-sizing: border-box;
  font-size: ${({ fontSize }) => fontSize};
  font-weight: ${({ fontWeight }) => fontWeight};
  letter-spacing: ${({ letterSpacing }) => letterSpacing};
  line-height: ${({ lineHeight }) => lineHeight};
  box-shadow: ${({ boxShadow }) => boxShadow};
  overflow: ${({ overflow }) => overflow};
  overflow-x: ${({ overflowX }) => overflowX};
  overflow-y: ${({ overflowY }) => overflowY};
  cursor: ${({ cursor }) => cursor};
  z-index: ${({ zIndex }) => zIndex};
  animation: ${({ animation }) => animation};
  transform: ${({ transform }) => transform};
  ${({ mixBlendMode }) => mixBlendMode && `mix-blend-mode : ${mixBlendMode}`};
  ::-webkit-scrollbar {
    width: ${({ scrollbarWidth }) => scrollbarWidth};
  }
`;
